artifacts_root: artifacts

data_ingestion:
  root_dir: artifcats/data_ingestion
  source_url: https://github.com/mspatke/Dummy-Repo/raw/main/winequality-data.zip
  local_data_file: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion 

